### ISSUE TITLE
Make imaginepy generate 4 images

### ISSUE THREAD

**Issue by mak448a** [mak448a/Stable-Diffusion-Bot#26]
All of the commands generate 4 images, so do this to be more consistent with the other commands.

**Comment by mishalhossin** [comment]
Yoink

**Comment by mak448a** [comment]
Probably should do this next

**Comment by mishalhossin** [comment]
> Probably should do this next

How to embed 4 images ?

**Comment by mak448a** [comment]
When you send it, just use `ctx.send(files=[discord.File(filename), discord.File(filename), discord.File(filename)])`

**Comment by mishalhossin** [comment]
yoink
