### ISSUE TITLE
Free OpenAI API proxy

### ISSUE THREAD

**Issue by mishalhossin** [mak448a/Stable-Diffusion-Bot#40]
https://gpt4.gravityengine.cc/api/openai/v1/chat/completions

Request example for chat style models

```shell
curl https://gpt4.gravityengine.cc/api/openai/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
  "model": "gpt-3.5-turbo",
  "messages": [{"role": "user", "content": "Hello, how are you doing today?"}],
  "temperature": 1,
  "max_tokens": 256,
  "top_p": 1,
  "frequency_penalty": 0,
  "presence_penalty": 0
}'
```

And for normal models:
```shell
curl https://gpt4.gravityengine.cc/api/openai/v1/completions  -H "Content-Type: application/json" -d '{
  "model": "text-davinci-003",
  "prompt": "Hello, my name is ",
  "temperature": 1,
  "max_tokens": 256,
  "top_p": 1,
  "frequency_penalty": 0,
  "presence_penalty": 0
}'
```

**Comment by mak448a** [comment]
I'm not sure why, but this command doesn't work when running in the terminal.

**Comment by mak448a** [comment]
Ah it's the `I'm` which is closing off the string

**Comment by mak448a** [comment]
But now I get ```{
  "error": {
    "message": "'messages' is a required property",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

**Comment by mak448a** [comment]
```shell
curl https://gpt4.gravityengine.cc/api/openai/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
  "model": "text-davinci-003",
  "prompt": "I am a ",
  "messages": [{"role": "user", "content": "Hello!"}]
  "temperature": 1,
  "max_tokens": 256,
  "top_p": 1,
  "frequency_penalty": 0,
  "presence_penalty": 0
}'
```

**Comment by mak448a** [comment]
There we go

**Comment by mishalhossin** [comment]
Idk man just use this

```
async def generate_response(prompt):
    base_url = 'https://gpt4.gravityengine.cc/api/openai/'
    error_base_url = 'https://askgpt.cn/api/openai/'
    arguments = '/v1/engines/text-davinci-003/completions'
    endpoint = base_url + arguments

    headers = {
        'Content-Type': 'application/json',
    }

    data = {
        'prompt': prompt,
        'max_tokens': 800,
        'temperature': 0.8
    }

    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(endpoint, headers=headers, json=data) as response:
                response_data = await response.json()
                return(response_data['choices'][0]['text'])
    except aiohttp.ClientError as error:
        print('Error making the request retrying with fallback model')
        endpoint = error_base_url + arguments
        async with aiohttp.ClientSession() as session:
            async with session.post(endpoint, headers=headers, json=data) as response:
                response_data = await response.json()
                return(response_data['choices'][0]['text'])
```

**Comment by mak448a** [comment]
I've edited your comment with the working code.

**Comment by mak448a** [comment]
Oh ok

> Idk man just use this
> 
> ```
> async def generate_response(prompt):
>     base_url = 'https://gpt4.gravityengine.cc/api/openai/'
>     error_base_url = 'https://askgpt.cn/api/openai/'
>     arguments = '/v1/engines/text-davinci-003/completions'
>     endpoint = base_url + arguments
> 
>     headers = {
>         'Content-Type': 'application/json',
>     }
> 
>     data = {
>         'prompt': prompt,
>         'max_tokens': 800,
>         'temperature': 0.8
>     }
> 
>     try:
>         async with aiohttp.ClientSession() as session:
>             async with session.post(endpoint, headers=headers, json=data) as response:
>                 response_data = await response.json()
>                 return(response_data['choices'][0]['text'])
>     except aiohttp.ClientError as error:
>         print('Error making the request retrying with fallback model')
>         endpoint = error_base_url + arguments
>         async with aiohttp.ClientSession() as session:
>             async with session.post(endpoint, headers=headers, json=data) as response:
>                 response_data = await response.json()
>                 return(response_data['choices'][0]['text'])
> ```

oh ok

**Comment by mak448a** [comment]
Should I use the davinci model in the chatbot?

**Comment by mak448a** [comment]
Got it. Posted a working test script to [here](https://github.com/mak448a/Stable-Diffusion-Bot/blob/main/davinci_003_test.py)

**Comment by mak448a** [comment]
By the way, how do you keep finding all this stuff?

**Comment by mishalhossin** [comment]
> By the way, how do you keep finding all this stuff?

https://github.com/LiLittleCat/awesome-free-chatgpt

**Comment by mak448a** [comment]
Added text-davinci-003
