### ISSUE TITLE
Add negative prompts

### ISSUE THREAD

**Issue by mak448a** [mak448a/Stable-Diffusion-Bot#46]
Add negative prompts to /imagine_horde and perhaps the other ones. We need to figure out a way to make optional arguments.

**Comment by mishalhossin** [comment]
> Add negative prompts to /imagine_horde and perhaps the other ones. We need to figure out a way to make optional arguments.

```
async def imagine(ctx, prompt: str, negative: str = None,
```

**Comment by mak448a** [comment]
Done! Thanks!
